apiVersion: v2
name: cert-manager-webhook-appscode
description: A webhook to use AppsCode DNS Proxy for Cloudflare as a DNS issuer for cert-manager
home: https://github.com/bytebuilders/cert-manager-webhook-appscode
type: application
version: 0.3.2
appVersion: 0.3.2
keywords:
- cert-manager
- letsencrypt
- tls
- civo
sources:
- https://github.com/bytebuilders/cert-manager-webhook-appscode
maintainers:
- email: rberrelleza@gmail.com
  name: Ramiro Berrelleza
  url: https://github.com/rberrelleza
